# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2020-02-07 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_auto_20200206_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortener',
            name='shortcode',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
